services:
  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - appnet
  client:
    container_name: client
    build: ./client
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
